name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: Reorganize asset paths for LHCI
        run: |
          mkdir lhci-root
          mv dist lhci-root/digital-text-explorer
      - name: run Lighthouse CI
        id: lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli@0.9.x
          lhci autorun
      - name: Job successful feedback
        if: ${{ success() }}
        run: |
          echo '### Successfully published to Deploy Now :white_check_mark:' >> $GITHUB_STEP_SUMMARY
          echo "Triggered by **${{ github.actor }}** ∙ deployed from **${{ github.ref_name }}**" >> $GITHUB_STEP_SUMMARY
          echo ' ' >> $GITHUB_STEP_SUMMARY
          echo "**Lighthouse results:**" >> $GITHUB_STEP_SUMMARY
          echo "Home page accessibility score: ${{ fromJSON(steps.lighthouse.outputs.manifest)[0].summary.accessibility }}" >> $GITHUB_STEP_SUMMARY
          echo "404 page accessibility score: ${{ fromJSON(steps.lighthouse.outputs.manifest)[1].summary.accessibility }}" >> $GITHUB_STEP_SUMMARY 
          echo "People page accessibility score: ${{ fromJSON(steps.lighthouse.outputs.manifest)[2].summary.accessibility }}" >> $GITHUB_STEP_SUMMARY 
          echo "Towns page accessibility score: ${{ fromJSON(steps.lighthouse.outputs.manifest)[3].summary.accessibility }}" >> $GITHUB_STEP_SUMMARY 
          echo "Guides page accessibility score: ${{ fromJSON(steps.lighthouse.outputs.manifest)[4].summary.accessibility }}" >> $GITHUB_STEP_SUMMARY 
          echo "Finding Documents page accessibility score: ${{ fromJSON(steps.lighthouse.outputs.manifest)[5].summary.accessibility }}" >> $GITHUB_STEP_SUMMARY 
          echo "Linguists Guide page accessibility score: ${{ fromJSON(steps.lighthouse.outputs.manifest)[6].summary.accessibility }}" >> $GITHUB_STEP_SUMMARY 
          echo "Document page accessibility score: ${{ fromJSON(steps.lighthouse.outputs.manifest)[7].summary.accessibility }}" >> $GITHUB_STEP_SUMMARY 
      - name: Job failed feedback
        if: ${{ failure() }}
        run: |
          echo '### Publishing to Deploy Now was not successful :cross:' >> $GITHUB_STEP_SUMMARY
          echo "Unfortunately, the deployment failed." >> $GITHUB_STEP_SUMMARY